Update license
atoum/phpunit-extension pull request #2
Opened 2016-09-28 09:43 UTC by stalmok

2016-09-28 09:48 UTC, jubianchi requested changes

2016-09-28 09:48 UTC, jubianchi commented on LICENSE
> +Copyright (c) 2010-2016, Frédéric Hardy.
> every mention to "Frédéric Hardy" must be replaced with "atoum contributors"
>
> -- #1

2016-09-28 09:48 UTC, jubianchi commented on LICENSE
> +    * Neither the name of Frédéric Hardy nor the names of its contributors
> every mention to "Frédéric Hardy" must be replaced with "atoum contributors"
>
> -- #1

2016-09-28 09:48 UTC, jubianchi commented on LICENSE
> +THIS SOFTWARE IS PROVIDED BY FRÉDÉRIC HARDY AND CONTRIBUTORS ``AS IS'' AND ANY
> every mention to "Frédéric Hardy" must be replaced with "atoum contributors"
>
> -- #1

Here everything has tu be uppercase

2016-09-28 09:48 UTC, jubianchi commented on LICENSE
> +DISCLAIMED. IN NO EVENT SHALL FRÉDÉRIC HARDY AND CONTRIBUTORS BE LIABLE FOR ANY
> every mention to "Frédéric Hardy" must be replaced with "atoum contributors"
>
> -- #1

Here everything has tu be uppercase

2016-09-28 10:07 UTC, jubianchi approved these changes

2016-09-28 10:08 UTC, jubianchi commented
Thanks!

2016-10-02 15:26 UTC, jubianchi commented
thanks @stalmok!

2016-10-02 15:26 UTC, merged

2016-10-03 15:38 UTC, stalmok commented
My pleasure!